#!/usr/bin/env python3
"""Generate the combined plugin's params.json, layout.conf and images/ from the two plugins' own sources.

  combo/params.json   wrapper switches (q_on, q_out), then the sequencer's params (keys prefixed "q_", names "Seq ..."),
                      then Maze Voice's params (module.json, unchanged keys)
  combo/layout.conf   the sequencer's tabs (keys prefixed), then the voice's tabs, plus the SEQ ON / OUTPUT controls
  combo/images/       both skins' images (identical where they overlap)

The sequencer core never sees the "q_" prefix: the wrapper strips it. Run by build.sh; the outputs are not committed.
"""
import json
import os
import re
import shutil
import sys

here = os.path.dirname(os.path.abspath(__file__))
root = os.path.join(here, "..")
MPC_VST = os.environ.get("MPC_VST", os.path.join(root, "..", "mpc-vst"))
sys.path.insert(0, os.path.join(MPC_VST, "adapters", "schwung"))
import module_params  # noqa: E402

P = "q_"

# ---- params ---------------------------------------------------------------------------------------------------------
seq = json.load(open(os.path.join(root, "sequencer", "vst", "params.json")))["params"]
voice, _ = module_params.load(os.path.join(root, "module.json"))

switches = [
    {"key": "q_on", "name": "Seq On", "options": ["OFF", "ON"], "default": 0},
    {"key": "q_out", "name": "Seq Output", "options": ["VOICE", "VOICE+MIDI", "MIDI ONLY"], "default": 0},
]
sq = []
for p in seq:
    p = dict(p)
    p["key"] = P + p["key"]
    p["name"] = "Seq " + p["name"]
    sq.append(p)
json.dump({"name": "Maze Combo", "params": switches + sq + voice}, open(os.path.join(here, "params.json"), "w"), indent=1)

# ---- layout ---------------------------------------------------------------------------------------------------------
def prefix_keys(line):
    if line.startswith("qlinks"):
        head, keys = line.split("=", 1)
        return head + "=" + ",".join(P + k.strip() for k in keys.split(","))
    return re.sub(r"\bkey=(\w+)", lambda m: "key=" + P + m.group(1), line)

seq_lines = open(os.path.join(root, "sequencer", "vst", "layout.conf")).read().splitlines()
voice_lines = open(os.path.join(root, "vst", "layout.conf")).read().splitlines()

def split_tabs(lines):
    head, tabs, cur = [], [], None
    for ln in lines:
        if ln.startswith("[tab "):
            cur = [ln]
            tabs.append(cur)
        elif cur is None:
            head.append(ln)
        else:
            cur.append(ln)
    return head, tabs

seq_head, seq_tabs = split_tabs(seq_lines)
voice_head, voice_tabs = split_tabs(voice_lines)
assert [h for h in voice_head if h and not h.startswith("#")] == [h for h in seq_head if h and not h.startswith("#")], \
    "the two skins' header settings differ; merge them by hand"

out = ["# GENERATED by combo/gen.py from sequencer/vst/layout.conf and vst/layout.conf: do not edit.",
       "# Sequencer tabs first (keys prefixed q_), then the voice tabs."]
out += [h for h in seq_head if h and not h.startswith("#")]
for ti, tab in enumerate(seq_tabs):
    body = [prefix_keys(l) for l in tab]
    if ti == 0:
        # master controls on the bottom strip of the SEQUENCERS tab, plus their own Q-Link page
        extra = ['toggle cx=560 cy=676 label="SEQ ON" key=q_on',
                 'enum_h cx=930 cy=676 sw=110 label="SEQ OUTPUT" key=q_out']
        at = next(i for i, l in enumerate(body) if l.startswith("qlinks"))
        body = body[:at] + extra + body[at:] + ['qlinks "SEQ MODE" = q_on,q_out,q_trig_mix,q_g_reset']
    if tab[0].startswith("[tab LFO]"):
        body[0] = "[tab SEQ LFO]"
    out += body
for tab in voice_tabs:
    out += tab
open(os.path.join(here, "layout.conf"), "w").write("\n".join(out) + "\n")

# ---- images ---------------------------------------------------------------------------------------------------------
dst = os.path.join(here, "images")
os.makedirs(dst, exist_ok=True)
for d in (os.path.join(root, "vst", "images"), os.path.join(root, "sequencer", "vst", "images")):
    for f in os.listdir(d):
        if f.endswith(".png") and "5frames" not in f:
            shutil.copy(os.path.join(d, f), os.path.join(dst, f))
shutil.copy(os.path.join(root, "vst", "skin.css"), os.path.join(here, "skin.css"))
print("combo: %d params, %d seq tabs + %d voice tabs" % (2 + len(sq) + len(voice), len(seq_tabs), len(voice_tabs)))
